### PR TITLE
Allow specifying private token through http request

### PR DESCRIPTION
**Pull request by LittleChimera**
This will allow to pass private token through http request. It would allow to share same service for multiple projects.

### CODE REVIEW

**Comment by shyiko** [comment]
Awesome :+1:. Thank you!

**Comment by shyiko** [comment]
@lukadante Should I publish a new version of `shyiko/gitlab-ci-build-on-merge-request` docker image or you have your own?

**Comment by LittleChimera** [comment]
It would be cool if you could. :)
Also I forgot to update README. Query parameter is also named private_token. I can submit another PR if you want me to update it.

**Comment by shyiko** [comment]
@lukadante no worries, I'll take care of it. `shyiko/gitlab-ci-build-on-merge-request:0.2.0` published :balloon:.

**Comment by shyiko** [comment]
@lukadante Thanks again :bowing_man:

**Comment by LittleChimera** [comment]
This is actually not working. I misplaced private_token for trigger token. I'd like to offer alternative solution when I get to it. In the meanwhile, perhaps it would be for the best to revert this PR.

**Comment by LittleChimera** [comment]
Actually, it is working, but it is not behaviour I hoped to achieve. 😬 
You can leave it as is, but I'll be working on another solution which would allow to pass trigger token and completly ignore private_token if one is not provided.

**Pull request merged**
